version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 99
    allow:
      - dependency-type: "direct"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 99
